---
# tasks file for ansible-role-freebsd_repos

- name: Create repo directory
  file:
    path: "{{ freebsd_repos_dir }}"
    state: directory
    mode: 0755

- name: Assert state field exists
  assert:
    that:
      - item.value.state == 'present' or item.value.state == 'absent'
  with_dict: "{{ freebsd_repos }}"

- name: Create repository configs
  template:
    src: repo.conf.j2
    dest: "{{ freebsd_repos_dir }}/{{ item.key }}.conf"
    mode: 0644
    validate: pkg -vv --config %s | grep -E '^[[:space:]]+{{ item.key }}:[[:space:]]+{'
  with_dict: "{{ freebsd_repos }}"
  when:
    - item.value.state == 'present'

- name: Remove repository configs
  file:
    path: "{{ freebsd_repos_dir }}/{{ item.key }}.conf"
    state: absent
  with_dict: "{{ freebsd_repos }}"
  when:
    - item.value.state == 'absent'
