---
# tasks file for ansible-role-freebsd_repos

- name: Create repo directory
  file:
    path: "{{ freebsd_repos_dir }}"
    state: directory
    mode: 0755

- name: Enable the repo
  template:
    src: repo.conf.j2
    dest: "{{ freebsd_repos_dir }}/{{ freebsd_repos_name }}.conf"
    mode: 0644
    validate: pkg -vv --config %s | grep -E '^[[:space:]]+{{ freebsd_repos_name }}:[[:space:]]+{'

- name: Disable default repo
  # XXX disable the default repo last only when other repo is validated and
  # created
  template:
    src: FreeBSD.conf.j2
    dest: "{{ freebsd_repos_dir }}/FreeBSD.conf"
    mode: 0644
    validate: pkg -vv --config %s
  when: freebsd_repos_disable_default_repository
